# Generated by Django 3.2.5 on 2021-07-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descicao', models.CharField(max_length=255)),
                ('aprovado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ponto Turistico',
                'verbose_name_plural': 'Pontos Turisticos',
            },
        ),
    ]
