# Generated by Django 3.2.5 on 2021-07-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='descicao',
            field=models.TextField(max_length=255),
        ),
    ]
