# Generated by Django 3.2.5 on 2021-07-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210705_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='descicao',
            new_name='descricao',
        ),
    ]
